name: Add issues and PRs to project

on:
  issues:
    types:
      - opened
      - transferred
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issues and PRs
    runs-on: ubuntu-20.04
    steps:
      - name: Add issue or PR
        uses: actions/add-to-project@v0.0.3
        with:
          project-url: https://github.com/users/bewuethr/projects/2
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
