name: Add issues and PRs to project

on:
  issues:
    types:
      - opened
      - transferred
  pull_request:
    types:
      - opened

jobs:
  add-to-pbb-project:
    name: Add issues and PRs to pbb project
    uses: bewuethr/workflows/.github/workflows/addtoproject.yml@main
    with:
      project-url: https://github.com/users/bewuethr/projects/2
    secrets:
      github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}

  add-to-hobbyist-project:
    name: Add issues to hobbyist project
    if: github.event_name == 'issues'
    uses: bewuethr/workflows/.github/workflows/addtoproject.yml@main
    with:
      project-url: https://github.com/users/bewuethr/projects/1
    secrets:
      github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
