name: Testing

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - id: set
        run: |
          echo "true=true" >> "$GITHUB_OUTPUT"
          echo "truequotes='true'" >> "$GITHUB_OUTPUT"
          echo 'truedoublequotes="true"' >> "$GITHUB_OUTPUT"
          echo "false=false" >> "$GITHUB_OUTPUT"
          echo "falsequotes='false'" >> "$GITHUB_OUTPUT"
          echo 'falsedoublequotes="false"' >> "$GITHUB_OUTPUT"

      - env:
          literal: ${{ steps.set.outputs.true == true }}
          fromjson: ${{ fromJSON(steps.set.outputs.true) == true }}
          literalquotes: ${{ steps.set.outputs.truequotes == true }}
          fromjsonquotes: ${{ fromJSON(steps.set.outputs.truequotes) == true }}
          fromjsonquotesstring: >-
            ${{ fromJSON(steps.set.outputs.truequotes) == 'true' }}
          literaldoublequotes: ${{ steps.set.outputs.truedoublequotes == true }}
          fromjsondoublequotes: ${{ fromJSON(steps.set.outputs.truedoublequotes) == true }}
          fromjsondoublequotesstring: >-
            ${{ fromJSON(steps.set.outputs.truedoublequotes) == 'true' }}
        run: |
          echo "steps.set.outputs.true == true: $literal"
          echo "fromJSON(steps.set.outputs.true) == true: $fromjson"
          echo "steps.set.outputs.truequotes == true: $literalquotes"
          echo "fromJSON(steps.set.outputs.truequotes) == true: $fromjsonquotes"
          echo "fromJSON(steps.set.outputs.truequotes) == 'true': $fromjsonquotesstring"
          echo "steps.set.outputs.truedoublequotes == true: $literaldoublequotes"
          echo "fromJSON(steps.set.outputs.truedoublequotes) == true: $fromjsondoublequotes"
          echo "fromJSON(steps.set.outputs.truedoublequotes) == 'true': $fromjsondoublequotesstring"

      - env:
          literal: ${{ steps.set.outputs.false == false }}
          fromjson: ${{ fromJSON(steps.set.outputs.false) == false }}
          literalquotes: ${{ steps.set.outputs.falsequotes == false }}
          fromjsonquotes: ${{ fromJSON(steps.set.outputs.falsequotes) == false }}
          fromjsonquotesstring: >-
            ${{ fromJSON(steps.set.outputs.falsequotes) == 'false' }}
          literaldoublequotes: ${{ steps.set.outputs.falsedoublequotes == false }}
          fromjsondoublequotes: ${{ fromJSON(steps.set.outputs.falsedoublequotes) == false }}
          fromjsondoublequotesstring: >-
            ${{ fromJSON(steps.set.outputs.falsedoublequotes) == 'false' }}
        run: |
          echo "steps.set.outputs.false == false: $literal"
          echo "fromJSON(steps.set.outputs.false) == false: $fromjson"
          echo "steps.set.outputs.falsequotes == false: $literalquotes"
          echo "fromJSON(steps.set.outputs.falsequotes) == false: $fromjsonquotes"
          echo "fromJSON(steps.set.outputs.falsequotes) == 'false': $fromjsonquotesstring"
          echo "steps.set.outputs.falsedoublequotes == false: $literaldoublequotes"
          echo "fromJSON(steps.set.outputs.falsedoublequotes) == false: $fromjsondoublequotes"
          echo "fromJSON(steps.set.outputs.falsedoublequotes) == 'false': $fromjsondoublequotesstring"
