name: Testing

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - id: set
        run: |
          echo "true=true" >> "$GITHUB_OUTPUT"
          echo "truequotes='true'" >> "$GITHUB_OUTPUT"

      - env:
          literal: ${{ steps.set.outputs.true == true }}
          fromjson: ${{ fromJSON(steps.set.outputs.true) == true }}
          literalquotes: ${{ steps.set.outputs.truequotes == true }}
          fromjsonquotes: ${{ fromJSON(steps.set.outputs.truequotes) == true }}
        run: |
          echo "steps.set.outputs.true == true: $literal"
          echo "fromJSON(steps.set.outputs.true) == true: $fromjson"
          echo "steps.set.outputs.truequotes == true: $literalquotes"
          echo "fromJSON(steps.set.outputs.truequotes) == true: $fromjsonquotes"
