name: Testing

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      envtrue: true
      envtruequotes: >-
        'true'
      envtruedoublequotes: >-
        "true"
    steps:
      - id: set
        run: |
          printf '%s\n'  >> "$GITHUB_OUTPUT" \
            "true=true" \
            "truequotes='true'"  \
            'truedoublequotes="true"'  \
            "false=false"  \
            "falsequotes='false'"  \
            'falsedoublequotes="false"'

      - name: Comparing "true" from output
        env:
          literal: ${{ steps.set.outputs.true == true }}
          fromjson: ${{ fromJSON(steps.set.outputs.true) == true }}
          literalquotes: ${{ steps.set.outputs.truequotes == true }}
          fromjsonquotes: ${{ fromJSON(steps.set.outputs.truequotes) == true }}
          fromjsonquotesstring: >-
            ${{ fromJSON(steps.set.outputs.truequotes) == 'true' }}
          literaldoublequotes: ${{ steps.set.outputs.truedoublequotes == true }}
          fromjsondoublequotes: ${{ fromJSON(steps.set.outputs.truedoublequotes) == true }}
          fromjsondoublequotesstring: >-
            ${{ fromJSON(steps.set.outputs.truedoublequotes) == 'true' }}
        run: |
          echo "steps.set.outputs.true == true: $literal"
          echo "fromJSON(steps.set.outputs.true) == true: $fromjson"
          echo "steps.set.outputs.truequotes == true: $literalquotes"
          echo "fromJSON(steps.set.outputs.truequotes) == true: $fromjsonquotes"
          echo "fromJSON(steps.set.outputs.truequotes) == 'true': $fromjsonquotesstring"
          echo "steps.set.outputs.truedoublequotes == true: $literaldoublequotes"
          echo "fromJSON(steps.set.outputs.truedoublequotes) == true: $fromjsondoublequotes"
          echo "fromJSON(steps.set.outputs.truedoublequotes) == 'true': $fromjsondoublequotesstring"

      - name: Comparing "false" from output
        env:
          literal: ${{ steps.set.outputs.false == false }}
          fromjson: ${{ fromJSON(steps.set.outputs.false) == false }}
          literalquotes: ${{ steps.set.outputs.falsequotes == false }}
          fromjsonquotes: ${{ fromJSON(steps.set.outputs.falsequotes) == false }}
          fromjsonquotesstring: >-
            ${{ fromJSON(steps.set.outputs.falsequotes) == 'false' }}
          literaldoublequotes: ${{ steps.set.outputs.falsedoublequotes == false }}
          fromjsondoublequotes: ${{ fromJSON(steps.set.outputs.falsedoublequotes) == false }}
          fromjsondoublequotesstring: >-
            ${{ fromJSON(steps.set.outputs.falsedoublequotes) == 'false' }}
        run: |
          echo "steps.set.outputs.false == false: $literal"
          echo "fromJSON(steps.set.outputs.false) == false: $fromjson"
          echo "steps.set.outputs.falsequotes == false: $literalquotes"
          echo "fromJSON(steps.set.outputs.falsequotes) == false: $fromjsonquotes"
          echo "fromJSON(steps.set.outputs.falsequotes) == 'false': $fromjsonquotesstring"
          echo "steps.set.outputs.falsedoublequotes == false: $literaldoublequotes"
          echo "fromJSON(steps.set.outputs.falsedoublequotes) == false: $fromjsondoublequotes"
          echo "fromJSON(steps.set.outputs.falsedoublequotes) == 'false': $fromjsondoublequotesstring"

      - name: Comparing "true" from environment
        env:
          literal: ${{ env.envtrue == true }}
          fromjson: ${{ fromJSON(env.envtrue) == true }}
          literalquotes: ${{ env.envtruequotes == true }}
          fromjsonquotes: ${{ fromJSON(env.envtruequotes) == true }}
          fromjsonquotesstring: >-
            ${{ fromJSON(env.envtruequotes) == 'true' }}
          literaldoublequotes: ${{ env.envtruedoublequotes == true }}
          fromjsondoublequotes: ${{ fromJSON(env.envtruedoublequotes) == true }}
          fromjsondoublequotesstring: >-
            ${{ fromJSON(env.envtruedoublequotes) == 'true' }}
        run: |
          echo "env.envtrue == true: $literal"
          echo "fromJSON(env.envtrue) == true: $fromjson"
          echo "env.envtruequotes == true: $literalquotes"
          echo "fromJSON(env.envtruequotes) == true: $fromjsonquotes"
          echo "fromJSON(env.envtruequotes) == 'true': $fromjsonquotesstring"
          echo "env.envtruedoublequotes == true: $literaldoublequotes"
          echo "fromJSON(env.envtruedoublequotes) == true: $fromjsondoublequotes"
          echo "fromJSON(env.envtruedoublequotes) == 'true': $fromjsondoublequotesstring"

      - name: Step that gets skipped, which might be a surprise
        if: '!steps.set.outputs.false'
        run: echo "I'd expect this to run"
