name: Testing

on:
  pull_request:
    type:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Only run on non-draft
    runs-on: ubuntu-22.04
    if: '! github.event.pull_request.draft'

    steps:
      - name: Print message
        run: echo Hello
