name: Test dynamic secret

on:
  workflow_dispatch:
    inputs:
      secret:
        description: Name of secret
        required: true
        default: FIRST
        type: choice
        options:
          - FIRST
          - SECOND

permissions: write-all

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - env:
          secret: ${{ secrets[inputs.secret] }}
        run: wc -c <<< "$secret"
