name: Appends "UPDATED" to specified issue's title

on:
  workflow_dispatch:
    inputs:
      NAME:
        type: string


jobs:
  update-issue:
    runs-on: ubuntu-latest
    steps:
      - env:
          name: ${{ github.event.inputs.NAME }}
        run: |
          gh issue edit --repo "$GITHUB_REPOSITORY" 1 \
              --title "$name - UPDATED"
