name: Appends "UPDATED" to specified issue's title

on:
  workflow_dispatch:
    inputs:
      NAME:
        type: string


jobs:
  update-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6.4.1
        env:
          name: ${{ github.event.inputs.NAME }}
        with:
          script: |
            const newTitle = process.env.name + ' - UPDATED';
            github.rest.issues.update({
              issue_number: 1,
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: newTitle
            });
