name: Run only on changes in specific directory

on:
  push:
    branches:
      - main
    paths:
      - ${{ vars.DIR }}/**
      - pandoc/**

jobs:
  job:
    name: Test job
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Hello there"
