name: Test dynamic variable names

on:
  workflow_dispatch:
    inputs:
      env:
        description: environment

jobs:
  testdynvar:
    name: Test dynamic variable names
    runs-on: ubuntu-22.04
    steps:
      - name: Print dynamic secret
        env:
          pass: ${{ secrets[format('PASSWORD_{0}', inputs.env)] }}
        run: |
          echo "The password for ${{ inputs.env }} is $pass"

  dynenv:
    name: Test dynamic environment name
    runs-on: ubuntu-22.04
    environment: ${{ inputs.env }}
    steps:
      - name: Print secret
        env:
          pass: ${{ secrets.PASSWORD }}
        run: |
          echo "The password for ${{ inputs.env }} is $pass"
