name: Test multi-line output parameters

on:
  workflow_dispatch:

jobs:
  test-multi-line:
    name: Test multi-line output
    runs-on: ubuntu-22.04
    steps:
      - name: Set output
        id: set
        run: |
          delim=$(tr -dc '[:upper:]' < /dev/urandom | head -c8)
          {
            echo "param<<$delim"
            curl wttr.in?format=j1
            echo "$delim"
          } >> "$GITHUB_OUTPUT"

      - name: Print output
        env:
          param: ${{ steps.set.outputs.param }}
        run: |
          printf '%s\n' "$param"
